FORMAT: 1A
HOST: https://api.netbanx.com/cardpayments/v1/

# NETBANX Card Payments API 

# Overview

Connect your application directly with our payment engine to process a full suite of methods that are REST-based – designed to be easy to understand and use. Ultimate control puts you in the driver’s seat.
* Choose an efficient, lightweight, and fast integration method to access our API.
* Implement a wide variety of REST-based API requests - including purchases, refunds, and authorization reversals.
* Obtain output in JSON format – it’s easy to parse in a large variety of Web and mobile applications.
* Use any language or platform to make requests through standard HTTP protocols.
